[book]
authors = ["Steven Hé (Sīchàng)"]
description = """Steven Hé (Sīchàng)'s personal website, \
for notes, blogs, CV, and fun.
Steven Hé (Sīchàng) is also known as Steven He, StevenHe, Sichang He, \
SichangHe, StevenSichangHe, 何思畅, or 何思暢.
"""
language = "en"
multilingual = false
src = "src"
title = "Steven Hé (Sīchàng)"

[build]
build-dir = "_site"

[output.html]
additional-css = ["theme/css/override.css"]
additional-js = ["theme/js/math.js"]
git-repository-url = "https://github.com/SichangHe/sichanghe.github.io"
smart-punctuation = true

[output.html.fold]
enable = true
level = 1

[output.html.playground]
copy-js = false
runnable = false

[preprocessor.header-footer]
headers = [{ padding = "<!-- toc -->\n" }]
footers = [
    { regex = "^blogs/", padding = """

[*Steven Hé (Sīchàng)'s Blogs*](/blogs/)

<script src="https://giscus.app/client.js" data-repo="SichangHe/sichanghe.github.io" data-repo-id="R_kgDOJoD14g"
    data-category="General" data-category-id="DIC_kwDOJoD14s4CflYo" data-mapping="title" data-strict="1"
    data-reactions-enabled="1" data-emit-metadata="0" data-input-position="top" data-theme="preferred_color_scheme"
    data-lang="en" data-loading="lazy" crossorigin="anonymous" async>
    </script>
""" },
    { regex = "^news/", padding = """

[*News | Steven Hé (Sīchàng)*](/news/)

<script src="https://giscus.app/client.js" data-repo="SichangHe/sichanghe.github.io" data-repo-id="R_kgDOJoD14g"
    data-category="General" data-category-id="DIC_kwDOJoD14s4CflYo" data-mapping="title" data-strict="1"
    data-reactions-enabled="1" data-emit-metadata="0" data-input-position="top" data-theme="preferred_color_scheme"
    data-lang="en" data-loading="lazy" crossorigin="anonymous" async>
    </script>
""" },
]
before = ["links", "toc"]

[preprocessor.toc]
before = ["katex"]

[preprocessor.katex]
after = ["links"]
include-src = true
throw-on-error = false
